### PR TITLE
Prepare changelog for v3.0.0 release

### PR DESCRIPTION
**Pull request by aphistic**
Update changelog for v3.0.0 release.

### CODE REVIEW

**Review by efritz — APPROVED** [review]
There's also a list of releases at the bottom you'll want to make an entry for

**Comment by aphistic** [comment]
> There's also a list of releases at the bottom you'll want to make an entry for

Oh, why do we have that? I would expect people to be able to do that themselves instead of duplicating info. I'm not opposed to it, just curious.

**Comment by efritz** [comment]
Ah, they link specifically to diffs between versions so people can see the code changes between upgrades.

**Comment by aphistic** [comment]
Is that something that needs to be explicitly included, or could they rely on the features of GitHub to get that if they want it? The reason I ask is to lower the overhead of doing a release and things to miss.

**Pull request merged**
